Create GraphQL endpoints for repositories
TabbyML/tabby pull request #1190
Opened 2024-01-10 19:54 UTC by boxbeam

Builds on top of the email-creds-graphql PR. Closes #1143.

Also in this PR: Refactored some common logic for converting GraphQL query parameters into our internal search filters

2024-01-11 02:15 UTC, wsxiaoys requested changes

2024-01-11 02:15 UTC, wsxiaoys commented on ee/tabby-webserver/src/schema/mod.rs
> +
Let's don't allow updating a repository (so front end user have to delete an repository and create a new one).

2024-01-11 02:15 UTC, wsxiaoys commented on ee/tabby-webserver/src/schema/repository.rs
> +    async fn update_repository(&self, id: ID, name: String, git_url: String) -> Result<bool>;
```suggestion
```

2024-01-11 02:15 UTC, wsxiaoys commented on ee/tabby-webserver/src/service/repository.rs
> +        self.update_repository(id.parse()?, name, git_url)
you might also remove DbConn's update_repository method since we don't plan to expose it.

2024-01-11 14:42 UTC, wsxiaoys requested changes
Otherwise LGTM

2024-01-11 14:42 UTC, wsxiaoys commented on ee/tabby-webserver/src/service/mod.rs
> +pub fn convert_vec<A: Into<B>, B>(v: Vec<A>) -> Vec<B> {
for oneliner like this, I prefer just write it down instead of reuse it as function.

2024-01-11 14:42 UTC, wsxiaoys commented on ee/tabby-webserver/src/service/mod.rs
> +pub fn graphql_params_to_filter(
```suggestion
pub fn graphql_pagination_to_filter(
```

nit

2024-01-12 04:39 UTC, wsxiaoys commented
Please resolve the conflicts

2024-01-12 16:21 UTC, wsxiaoys approved these changes

2024-01-12 16:21 UTC, wsxiaoys commented
cc @darknight for comments

2024-01-13 13:03 UTC, darknight commented
LGTM :)

2024-01-13 13:12 UTC, merged

2024-01-13 13:15 UTC, wsxiaoys commented
@boxbeam please rebase this pr against main