fix(webserver): Disallow resetting a password to the same value
TabbyML/tabby pull request #1619
Opened 2024-03-04 18:47 UTC by boxbeam

Fixes TAB-549

2024-03-04 19:02 UTC, wsxiaoys requested changes

2024-03-04 19:05 UTC, boxbeam commented on ee/tabby-webserver/src/schema/mod.rs
> +        {}
Tried, there is no `must_not_match` validation

2024-03-05 08:08 UTC, wsxiaoys commented on ee/tabby-webserver/src/schema/mod.rs
> +        {}
could implement a custom one? just like https://sourcegraph.com/github.com/TabbyML/tabby@7dee3b188fda550b743bc2a89edd4f619980a5c1/-/blob/ee/tabby-webserver/src/schema/auth.rs?L142

2024-03-05 08:17 UTC, wsxiaoys commented on ee/tabby-webserver/src/schema/mod.rs
> +        input
the value is not used

2024-03-05 18:17 UTC, boxbeam commented on ee/tabby-webserver/src/schema/mod.rs
> +        {}
Marking as resolved, saw that you added and deleted a comment - probably noticed it can only handle the one field, not compare it against others

2024-03-05 20:52 UTC, wsxiaoys requested changes
Otherwise LGTM

2024-03-05 20:52 UTC, wsxiaoys commented on ee/tabby-webserver/src/service/auth.rs
> +            return Err(anyhow!("New password cannot match old password").into());
```suggestion
            return Err(anyhow!("New password cannot be the same as your current password").into());
```

2024-03-05 20:52 UTC, wsxiaoys commented on ee/tabby-webserver/src/service/auth.rs
> +            return Err(anyhow!("New password cannot match old password").into());
ditto

2024-03-06 03:20 UTC, wsxiaoys commented
@boxbeam please resolve

2024-03-06 16:57 UTC, merged