docs: add windows installation
TabbyML/tabby pull request #1640
Opened 2024-03-07 08:02 UTC by wwayne

fix #1179

2024-03-07 08:10 UTC, wsxiaoys commented on website/docs/installation/windows/index.mdx
> +* If you are using a GPU-enabled system, download the **tabby_x86_64-windows-msvc-cuda{VERSION}.exe** file, replacing {VERSION} with the appropriate CUDA version for your system.
use a concrete version number (e.g 11.7) as an example.

2024-03-07 08:10 UTC, wsxiaoys commented on website/docs/installation/windows/index.mdx
> +```
add more steps to verify installation success (e.g open swagger page and run some inference)

2024-03-07 08:25 UTC, wsxiaoys commented on website/docs/installation/windows/index.mdx
> +Running Tabby on Windows without WSL or Docker.
```suggestion
Running Tabby on Windows using Tabby's exe distribution
```

2024-03-07 09:36 UTC, wwayne commented
updated based on the feedbacks

2024-03-09 00:36 UTC, gyxlucy commented on website/docs/installation/windows/index.mdx
> +* Check your local CUDA version by running the following command in a command prompt or PowerShell window:
What version is needed? Is there a minimum requirement?

2024-03-09 00:37 UTC, gyxlucy requested changes
One question for clarification

2024-03-09 02:10 UTC, wwayne commented on website/docs/installation/windows/index.mdx
> +* Check your local CUDA version by running the following command in a command prompt or PowerShell window:
Looks both 11 and 12 are suppoted?

This is CUDA download page
![屏幕截图 2024-03-09 100119](https://github.com/TabbyML/tabby/assets/5305874/8e00e949-02b6-403a-9687-53ef6d8439a3)

I add a new tip to the list
`Ensure that you have CUDA version 11 or higher installed.`

2024-03-09 02:11 UTC, wwayne commented on website/docs/installation/windows/index.mdx
> +* Check your local CUDA version by running the following command in a command prompt or PowerShell window:
@icycodes if you can help to double confirm? thanks

2024-03-09 02:11 UTC, wsxiaoys commented on website/docs/installation/windows/index.mdx
> +* Check your local CUDA version by running the following command in a command prompt or PowerShell window:
cuda 11 is good enough.

2024-03-12 09:39 UTC, gyxlucy approved these changes

2024-03-12 12:05 UTC, merged