feat(webserver): allow specifying the url base for self-hosted github/gitlab instances
TabbyML/tabby pull request #2196
Opened 2024-05-20 19:11 UTC by boxbeam

2024-05-20 19:14 UTC, wsxiaoys requested changes

2024-05-20 19:14 UTC, wsxiaoys commented on ee/tabby-db/migrations/0029_merged-provider-tables.up.sql
> +    url_base TEXT NOT NULL,
```suggestion
    api_base TEXT,
```

Making this a nullable field, and for github / gitlab SAAS, it shall be null.

Please create separate `kind` enum for github self hosted / gitlab self hosted.

2024-05-20 21:05 UTC, wsxiaoys commented on ee/tabby-schema/src/schema/mod.rs
`github_repositories` / `gitlab_repositories` also need to be updated (they shall only return saas version repos).

`self_hosted_github` / `self_hosted_gitlab` need to be added

2024-05-20 21:07 UTC, wsxiaoys commented on ee/tabby-schema/src/schema/mod.rs
another option would be make `provider_id: Vec<>` non empty - since we distinguish self hosted / non self hosted at provider level. And i believe FE always pass in a `provider_id`.

2024-05-20 21:09 UTC, boxbeam commented on ee/tabby-schema/src/schema/mod.rs
So do you want me to leave it unchanged and they will pass the provider IDs?

2024-05-20 21:11 UTC, wsxiaoys commented on ee/tabby-schema/src/schema/mod.rs
Will need to add a check that ensure `provider_id` is non empty.

2024-05-20 21:12 UTC, boxbeam commented on ee/tabby-schema/src/schema/mod.rs
Resolution: Adding `self_hosted_github_repositories` / same for gitlab

2024-05-21 17:14 UTC, boxbeam commented on ee/tabby-schema/graphql/schema.graphql
>    GIT
cc @liangfung new endpoints for self hosted integrations

2024-05-21 21:12 UTC, wsxiaoys commented
Otherwise LGTM

2024-05-21 21:28 UTC, wsxiaoys commented on ee/tabby-schema/src/schema/integration.rs
> +                bail!("Self-hosted gitlab requires a user-specified API base URL")
should return self.api_base instead of bail.

2024-05-21 21:41 UTC, wsxiaoys approved these changes

2024-05-21 21:48 UTC, merged