fix(webserver): improve error handling and report stdout for doc indexing pipeline
TabbyML/tabby pull request #2462
Opened 2024-06-20 20:58 UTC by boxbeam

New error will suggest double-checking whether katana is installed when the job fails

2024-06-20 20:59 UTC, boxbeam commented
Successful run:

![image](https://github.com/TabbyML/tabby/assets/14198267/7aa1a13d-ff66-4e54-b533-692ae20e1231)

Failed run:

![image](https://github.com/TabbyML/tabby/assets/14198267/26dac8f5-316e-430e-af53-9d1f07c3da3e)

2024-06-21 01:55 UTC, wsxiaoys requested changes

2024-06-21 01:55 UTC, wsxiaoys commented on crates/tabby-scheduler/src/lib.rs
> +    embedding: Arc<dyn Embedding>,
```suggestion
    start_urls: &[String],
    embedding: Arc<dyn Embedding>,
    on_process_url: impl Fn(String) -> F,
```

2024-06-21 01:55 UTC, wsxiaoys commented on ee/tabby-webserver/src/service/background_job/web_crawler.rs
> +                async move { cprintln!(job_logger, "{url}") }
Please write more informative logs since it's user facing, maybe something like: "Fetching {url}"

2024-06-21 04:56 UTC, wsxiaoys commented
note you don't have to run `update-ui` in this PR, it'll be handled as part of release process

2024-06-21 14:41 UTC, boxbeam commented
> note you don't have to run `update-ui` in this PR, it'll be handled as part of release process
> 

I see, I had to run it to see the changes locally and confirm the fix. Next time I can just not stage those changes.

2024-06-21 15:00 UTC, merged