feat(ui): add code search functionality
TabbyML/tabby pull request #2587
Opened 2024-07-05 08:26 UTC by liangfung

## Changes
Add code search functionality to code browser. When searching, it will search the codebase and display the search results based on the repo and branch currently selected by the user.

### preview
https://jam.dev/c/79e6c34f-7689-4669-8efd-1247153123f9

2024-07-08 04:22 UTC, wwayne commented
The shortcut doesn't seem to work (pressing 'S' does not focus on the search field)

<img width="235" alt="Screenshot 2024-07-08 11 37 03" src="https://github.com/TabbyML/tabby/assets/5305874/1d54013b-86f4-4dc9-906e-d34acd5859be">

2024-07-08 04:23 UTC, wwayne commented
search `react` -> click a link in the result -> browser back -> empty
https://jam.dev/c/0aa4e9e9-36d9-4bb7-99fe-1f512deb9833

2024-07-08 09:37 UTC, wwayne requested changes
Code LGTM, but 2 UI bugs, left comments above

2024-07-09 01:20 UTC, wsxiaoys commented on ee/tabby-ui/app/files/components/code-search-bar.tsx
> +          placeholder="Search repository..."
```suggestion
          placeholder="Search for code..."
```

2024-07-09 08:46 UTC, wsxiaoys approved these changes

2024-07-09 09:31 UTC, merged