feat(ui): support selecting indexed repositories in answer engine
TabbyML/tabby pull request #2594
Opened 2024-07-08 08:24 UTC by liangfung

### Changes
Support selecting indexed repositories to enhance answer engine.

### Screen recoed
https://jam.dev/c/28fe7097-908a-46fc-a3c0-1faf6a33a783

### Preview
#### With indexed repos
<img width="954" alt="image" src="https://github.com/TabbyML/tabby/assets/17516233/b3c97518-8cff-4bb8-bc49-9cbf6d7f2646">

#### Has no indexed repos
<img width="931" alt="image" src="https://github.com/TabbyML/tabby/assets/17516233/7ab943c7-772b-4d74-b5a8-7c1f37058029">

2024-07-08 09:55 UTC, wwayne commented on ee/tabby-ui/app/search/components/search.tsx
> +                isFollowup
👍

2024-07-09 00:59 UTC, wsxiaoys commented on ee/tabby-ui/components/textarea-search.tsx
> +        Select indexed repositories to enhance the answer engine
```suggestion
    Effortlessly interact with your repositories for contextualized search and assistance.
```

2024-07-09 01:00 UTC, wsxiaoys commented on ee/tabby-ui/components/textarea-search.tsx
> +          <p className="font-semibold">No indexed repositories</p>
```suggestion
          <p className="font-semibold">No repositories</p>
```

2024-07-09 01:02 UTC, wsxiaoys requested changes

2024-07-09 01:02 UTC, wsxiaoys commented on ee/tabby-ui/components/textarea-search.tsx
> +            Add repositories
```suggestion
    Connect
```

2024-07-09 01:02 UTC, wsxiaoys commented on ee/tabby-ui/components/textarea-search.tsx
> +                    : 'Select repositories'}
```suggestion
                    : 'Select repository'}
```

2024-07-09 01:02 UTC, wsxiaoys commented on ee/tabby-ui/components/textarea-search.tsx
> +              <CommandInput placeholder="Search repositories" />
```suggestion
              <CommandInput placeholder="Search" />
```

2024-07-14 07:37 UTC, merged