refactor(search): add config
TabbyML/tabby pull request #2875
Opened 2024-08-14 06:26 UTC by xxs-wallace

one of https://github.com/TabbyML/tabby/issues/2783

2024-08-14 07:04 UTC, wsxiaoys requested changes

2024-08-14 07:04 UTC, wsxiaoys commented on ee/tabby-webserver/src/service/repository/mod.rs
> +            RepositoryKind::Git | RepositoryKind::GitConfig => self.git().get_repository(id).await,
will this be working? can you test this behavior locally?

see https://tabby.tabbyml.com/docs/administration/context/#adding-a-repository-through-configuration-file for a `config.toml` based configuration, and verify it in `Code Browser`

2024-08-14 07:18 UTC, wsxiaoys commented
Please also write more informative commit message - `add config` is too abstract to represent the intent behind the PR.

2024-08-14 07:46 UTC, wsxiaoys commented on ee/tabby-webserver/src/service/repository/mod.rs
>              if let Ok(index) = config_id_to_index(id) {
if it's an GitConfig but not able to run `config_id_to_index` successfully, we shall bail instead?

2024-08-15 02:15 UTC, wsxiaoys commented
> Please also provide jam.dev screen recording for easier communication, see https://github.com/TabbyML/tabby/pull/2847 for an example.

Please add a screen recording, otherwise LGTM

2024-08-15 08:32 UTC, xxs-wallace commented
https://jam.dev/c/f0165bd9-0378-430a-8c6d-f6f69b114f3c

2024-08-16 05:51 UTC, merged