feat(email): support self-signed smtp cert from env
TabbyML/tabby pull request #3035
Opened 2024-09-01 07:08 UTC by zwpaper

2024-09-01 22:48 UTC, wsxiaoys commented on ee/tabby-schema/src/schema/mod.rs
> +
Let's just use `Other` error type

2024-09-01 22:48 UTC, wsxiaoys commented on ee/tabby-webserver/src/service/email/mod.rs
> +    if let Ok(cert_path) = std::env::var("TABBY_EMAIL_CERT_PATH") {
```suggestion
    if let Ok(cert_path) = std::env::var("TABBY_WEBSERVER_EMAIL_CERT") {
```

2024-09-01 22:49 UTC, wsxiaoys commented on ee/tabby-webserver/src/service/email/mod.rs
> +        let cert = Certificate::from_pem(&std::fs::read(cert_path)?)
```suggestion
        let cert = Certificate::from_pem(&cert_string)
```

2024-09-01 22:49 UTC, wsxiaoys requested changes
Otherwise LGTM

2024-09-02 16:13 UTC, zwpaper commented
hi @wsxiaoys, comments fixed, PTAL, thanks

2024-09-02 16:40 UTC, merged