draft: feat(core, webserver): add /v1/models api
TabbyML/tabby pull request #3164
Opened 2024-09-19 00:33 UTC by antimonyGu

ticket
#3097

2024-09-19 00:36 UTC, wsxiaoys requested changes

2024-09-19 00:36 UTC, wsxiaoys commented on crates/tabby/src/routes/server_setting.rs
Please create new file for this endpoint.

2024-09-19 00:36 UTC, wsxiaoys commented on crates/tabby/src/serve.rs
> +            .route("/v1/models", routing::get(routes::models));
move this to line router created in line 249

2024-09-20 00:57 UTC, antimonyGu commented
Fixing comment and will update.

2024-09-24 04:24 UTC, wsxiaoys requested changes
Otherwise LGTM

2024-09-24 04:24 UTC, wsxiaoys commented on crates/tabby/src/routes/supported_models.rs
> +pub async fn models() -> Json<Vec<String>> {
return an json object instead, e.g

```
{
  completion: [...],
  chat: [...],
}
```

2024-09-24 04:24 UTC, wsxiaoys commented on crates/tabby/src/routes/supported_models.rs
> +    }
no need to append embedding models

2024-09-25 02:51 UTC, wsxiaoys requested changes

2024-09-25 02:51 UTC, wsxiaoys commented on crates/tabby/src/routes/mod.rs
> +mod supported_models;
```suggestion
mod models;
```

2024-09-25 02:51 UTC, wsxiaoys commented on crates/tabby/src/routes/supported_models.rs
> +pub struct SupportedModel {
```suggestion
pub struct ModelInfo {
```

2024-09-25 02:51 UTC, wsxiaoys commented on crates/tabby/src/routes/supported_models.rs
> +        Config::load().expect("Config file should be exist").model;
Config shall be passed as a state from `serve.rs`.

See https://github.com/TabbyML/tabby/blob/80f34f9d8f7e1fac3cb27aa193456daed265347c/crates/tabby/src/routes/health.rs#L18 as an example (HealthState).

2024-09-25 02:51 UTC, wsxiaoys commented on crates/tabby/src/routes/supported_models.rs
> +    };
```suggestion
    let mut completion = None;
    let mut chat = None;
```

2024-09-25 02:51 UTC, wsxiaoys commented on crates/tabby/src/routes/supported_models.rs
> +        }
```suggestion
        if let Some(models) = completion_http_config.supported_models {
            completion = Some(models.clone());
        }
```

2024-09-25 02:51 UTC, wsxiaoys commented on crates/tabby/src/routes/supported_models.rs
> +    chat: Vec<String>,
```suggestion
    completion: Option<Vec<String>>,
    chat: Option<Vec<String>>,
```

2024-09-26 05:14 UTC, wsxiaoys commented on crates/tabby/src/routes/models.rs
> +}
implement `From<Config>` for `ModelInfo`

2024-09-26 05:14 UTC, wsxiaoys commented on crates/tabby/src/routes/models.rs
> +pub async fn models(State(state): State<Arc<tabby_common::config::Config>>) -> Json<ModelInfo> {
```suggestion
pub async fn models(State(state): State<Arc<ModelInfo>) -> Json<ModelInfo> {
```

2024-09-26 05:14 UTC, wsxiaoys commented on crates/tabby/src/serve.rs
> +            .with_state(Arc::new(config.clone()))
convert config to ModelInfo using `.into`

2024-09-26 05:15 UTC, wsxiaoys approved these changes
Otherwise LGTM

2024-09-30 03:20 UTC, merged