fix(vscode): check weather proxy url is in noProxy field
TabbyML/tabby pull request #3440
Opened 2024-11-19 20:55 UTC by antimonyGu

# Test
Setting vscode `noProxy` and `Proxy` fields with "http://localhost:8000", `proxy.url` will be ""(empty string).

close #3360

2024-11-20 00:04 UTC, wsxiaoys commented on clients/vscode/src/Config.ts
> +    if (this.noProxy.includes(httpsProxy) || this.noProxy.includes(httpProxy)) return "";
move to function `buildClientProvidedConfig`

2024-11-20 05:09 UTC, wsxiaoys commented on clients/vscode/src/Config.ts
> +  disableProxy?: boolean;
```suggestion
  useVSCodeProxy?: boolean;
```

2024-11-20 05:09 UTC, wsxiaoys commented on clients/tabby-agent/src/http/proxy.ts
> +      // "item1, item2  item3".split(/,|\s+/). Results in: ["item1", "item2", "item3"]
```suggestion
```

2024-11-21 07:40 UTC, icycodes commented on clients/vscode/src/Config.ts
> +    return advancedSettings["useVSCodeProxy"] || true;
```suggestion
    return advancedSettings["useVSCodeProxy"] ?? true;
```
`anything || true` will always return `true`.

2024-11-21 07:43 UTC, icycodes requested changes
Please update the PR description.

2024-11-22 00:55 UTC, icycodes approved these changes

2024-11-22 00:56 UTC, merged