feat(chat): allow share a thread from Chat panel sidebar
TabbyML/tabby pull request #3479
Opened 2024-11-27 10:58 UTC by liangfung

## Screen record
https://jam.dev/c/f3ba3060-ef93-49ea-905e-2977eac47811

2024-11-27 13:29 UTC, wsxiaoys commented
LGTM for `ee/tabby-schema/src/schema/mod.rs`

2024-11-30 08:49 UTC, Sma1lboy requested changes
Otherwise, LGTM

2024-11-30 08:49 UTC, Sma1lboy commented on ee/tabby-ui/app/chat/page.tsx
> +    const hasCapability = true
Now we can use the `hasCapability` check from the client API.

2024-12-02 05:25 UTC, wsxiaoys commented on clients/tabby-chat-panel/src/index.ts
> +  onOpenExternal: (url: string) => Promise<boolean>
```suggestion
  onOpenExternal?: (url: string) => Promise<boolean>
```

2024-12-03 02:00 UTC, Sma1lboy approved these changes
LGTM

2024-12-03 03:04 UTC, merged