feat(chat-panel): add provide at function feature api in chat panel
TabbyML/tabby pull request #3601
Opened 2024-12-20 09:16 UTC by Sma1lboy

2024-12-24 01:25 UTC, Sma1lboy commented
@wsxiaoys ping

2025-01-06 01:46 UTC, wsxiaoys requested changes

2025-01-06 01:46 UTC, wsxiaoys commented on clients/tabby-chat-panel/src/index.ts
> +  provideFileAtInfo?: (opts?: AtInputOpts) => Promise<FileInfo[] | null>
```suggestion
  listFileInWorkspace?: (opts?: ListFileInput) => Promise<FileRange[] | null>
```

2025-01-06 01:46 UTC, wsxiaoys commented on clients/tabby-chat-panel/src/index.ts
> +  provideRangeContent?: (info: FileInfo) => Promise<string | null>
```suggestion
  readFileContent?: (range: FileRange) => Promise<string | null>
```

2025-01-06 01:46 UTC, wsxiaoys commented on clients/tabby-chat-panel/src/index.ts
> +export interface FileInfo {
```suggestion
export interface FileRange {
```

2025-01-06 01:46 UTC, wsxiaoys commented on clients/tabby-chat-panel/src/index.ts
> +  filename: string
```suggestion
```

2025-01-06 01:59 UTC, wsxiaoys commented on clients/tabby-chat-panel/src/index.ts
> +  listFileInWorkspace?: (opts?: AtInputOpts) => Promise<FileRange[] | null>
```suggestion
  listFileInWorkspace?: (option?: listFileOption) => Promise<FileRange[] | null>
```

2025-01-17 08:06 UTC, merged