feat(vscode): add shortcut hint in codeLens title
TabbyML/tabby pull request #3637
Opened 2024-12-31 21:56 UTC by antimonyGu

- Recording: https://jam.dev/c/97d046de-ee6f-42b5-8bef-06dfbbd934d0.
- To do: Read keybinds from LSP client.

2025-01-02 08:48 UTC, icycodes commented
Please consider implementing this in the VSCode scope first. This will avoid adding an API to the Tabby-agent protocol.

You can try adding the processing in [CodeLensMiddleware.ts](https://github.com/TabbyML/tabby/blob/main/clients/vscode/src/lsp/CodeLensMiddleware.ts) to modify the CodeLens title.

2025-01-06 11:21 UTC, icycodes requested changes
Please rebase on the `main` branch and revert any unrelated changes.

2025-01-06 11:21 UTC, icycodes commented on clients/vscode/src/lsp/CodeLensMiddleware.ts
> +      // TODO: read ~/.config/Code/User/keybindings.json from LSP client, then send to LSP server to avoid hardcode.
```suggestion
      // FIXME: Read the user keybinding config to check if there is a customized keybinding.
```

2025-01-06 11:21 UTC, icycodes commented on clients/vscode/src/lsp/CodeLensMiddleware.ts
> +      const acceptShortcut = isBrowser ? "" : ` (${process.platform === "darwin" ? "cmd+enter" : "ctrl+enter"})`;
Please keep the keybinding hint label consistent with VSCode's style.  
- On Linux/Windows, `Ctrl+Enter` should be capitalized.  
- On macOS, Unicode symbols like `⌘` should be used.  
Please refer to the [VSCode source](https://github.com/microsoft/vscode/blob/main/src/vs/base/common/keybindingLabels.ts#L55) for more details.

2025-01-06 19:20 UTC, antimonyGu commented on clients/vscode/src/lsp/CodeLensMiddleware.ts
> +      // TODO: read ~/.config/Code/User/keybindings.json from LSP client, then send to LSP server to avoid hardcode.
Reference: [How to read keybindings](https://stackoverflow.com/questions/40682100/vs-code-extension-programmatically-find-keybindings).

2025-01-06 19:28 UTC, antimonyGu commented on clients/vscode/src/lsp/CodeLensMiddleware.ts
> +      .filter((codeLens): codeLens is CodeLens => codeLens !== null);
Reverted.

2025-01-13 02:39 UTC, icycodes requested changes

2025-01-13 02:39 UTC, icycodes commented on clients/vscode/src/lsp/CodeLensMiddleware.ts
> +      const acceptShortcut = isBrowser ? "" : ` (${process.platform === "darwin" ? "⌘+enter" : "Ctrl+enter"})`;
```suggestion
      const acceptShortcut = isBrowser ? "" : ` (${process.platform === "darwin" ? "⌘+Enter" : "Ctrl+Enter"})`;
```

2025-01-13 02:39 UTC, icycodes commented on clients/vscode/src/lsp/CodeLensMiddleware.ts
> +      const discardShortcut = isBrowser ? "" : ` (esc)`;
```suggestion
      const discardShortcut = isBrowser ? "" : ` (Esc)`;
```

2025-01-13 02:39 UTC, icycodes commented on clients/tabby-agent/src/codeLens.ts
>                  command: "tabby/chat/edit/resolve",
Please revert changes in this file.

2025-03-18 09:43 UTC, icycodes commented
I am closing this PR as #3895 has been merged.

2025-03-18 09:43 UTC, closed without merging