Patch 1
TabbyML/tabby pull request #453
Opened 2023-09-16 17:48 UTC by samsja

# Context

this PR include some suggestion for the vim plugin documentation of Tabby

2023-09-17 03:10 UTC, wsxiaoys requested changes

2023-09-17 03:10 UTC, wsxiaoys commented on clients/vim/README.md
> +TabbyML is compatible with both Vim and NeoVim text editor via a plugin.
```suggestion
Tabby is compatible with both Vim and NeoVim text editor via a plugin.
```

2023-09-17 03:10 UTC, wsxiaoys commented on clients/vim/README.md
> +You will need to edit your vim config file (`~/.vimrc` for vim and `~/.config/nvim/init.vim` for neovim) and copy paste the following lines in it (between the `plug#begin` and `plug#end` lines)
```suggestion
You will need to edit `~/.config/nvim/init.vim` for and copy paste the following lines in it.

2023-09-17 03:10 UTC, wsxiaoys commented on clients/vim/README.md
> +If you se `Tabby cannot connect to the server` it means that you need to start the tabbyML server first. Refer to this [documentation](https://tabby.tabbyml.com/docs/installation/)
```suggestion
If you se `Tabby cannot connect to the server` it means that you need to start the tabby server first. Refer to this [documentation](https://tabby.tabbyml.com/docs/installation/)
```

2023-09-17 03:11 UTC, wsxiaoys commented on clients/vim/README.md
> +If you se `Tabby cannot connect to the server` it means that you need to start the tabbyML server first. Refer to this [documentation](https://tabby.tabbyml.com/docs/installation/)
A few nits

2023-09-18 07:20 UTC, wsxiaoys approved these changes

2023-09-18 08:24 UTC, icycodes approved these changes
Thank you for your excellent documentation!

2023-09-18 08:26 UTC, merged