feat: proxy server address mapping to the model server
TabbyML/tabby pull request #461
Opened 2023-09-19 08:24 UTC by hufeng

![image](https://github.com/TabbyML/tabby/assets/533008/8ec41f3e-f2e3-4c5b-92a8-f7301f5f888d)

Before the Tabby service, if there is nginx's reverse proxy service, users can access Tabby's services through domain names. Currently, swagger only has https://playground.app.tabbyml.com and local service options, and cannot perform service completion through domain names.

current server：
![image](https://github.com/TabbyML/tabby/assets/533008/149aa46a-4da0-4733-b7f6-a117ded2cdeb)

add proxy server
![image](https://github.com/TabbyML/tabby/assets/533008/bf261ec3-0267-4e32-a693-b94d88d13e95)

2023-09-20 04:41 UTC, wsxiaoys requested changes
Thanks for the PR, overall looks good. But for a configuration like this I would really prefer it being part of the `config.toml` rather than as a command line argument interface.

Could you add a new sub struct `swagger` in [Config](https://github.com/TabbyML/tabby/blob/main/crates/tabby-common/src/config.rs#L12C6-L12C6) here? the pesudo code would be something like below:

```rust
pub struct Config {
  pub repositories: Vec<Repository>,
  pub swagger: SwaggerConfig
}

pub struct SwaggerConfig {
  pub server_url: Option<String>
}
```

2023-09-21 06:32 UTC, wsxiaoys reviewed
Otherwise LGTM

2023-09-21 06:32 UTC, wsxiaoys commented on crates/tabby/src/serve/mod.rs
>      }
```suggestion
    if server_url.is_none() {
        return doc;
    }
    let server_url = server_url.unwrap();
```

2023-09-21 06:50 UTC, hufeng commented on crates/tabby/src/serve/mod.rs
>      }
Yes

2023-09-21 06:54 UTC, wsxiaoys approved these changes

2023-09-21 07:06 UTC, merged